name: Deploying Shivam Baghla's Digital Home
run-name: ${{ github.actor }} pushed to master

on:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
  workflow_dispatch:

permissions:
  pages: write
  id-token: write
  contents: write

jobs:
  generate-and-deploy:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: "Action Details üöÄ"
        run: |
          echo "
          Runner OS: ${{ runner.os }}
          Triggered Event: ${{ github.event_name }}
          Event By: ${{ github.actor }}
          Branch: ${{ github.ref }}
          Repo: ${{ github.repository }}
          "
      - name: Install Pandoc
        uses: pandoc/actions/setup@main
        with:
          version: 2.19
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List all files
        run: ls -al
      - name: Build (Will convert all MDs to HTMLs and move additional files)
        run: |
          rm -rf docs
          mkdir -p docs
          for i in $(find . -type f \( -name "*.avif" -o -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" -o -name "*.gif" -o -name "*.html" \)) ; do
            echo "$i"
            target_dir="docs/$(dirname $i)"
            mkdir -p "$target_dir"
            mv $i "$target_dir/"
          done
          for i in $(find . -type f -name "*.md") ; do
            echo "$i"
            target_dir="docs/$(dirname $i)"
            mkdir -p "$target_dir"
            pandoc -s $i -o "$target_dir/$(basename $i .md).html" --css=theme.css --self-contained
            rm $i
          done

      - name: List all files
        run: ls -al
      - name: Commit generated folder
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git add docs
          git commit -m "Generate and deploy folder" --no-verify
      - name: Push changes
        run: |
          git push origin HEAD:master
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./docs"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - run: echo "üçè This job's status is ${{ job.status }}."
