name: generate html from MDs under md directory
run-name: ${{ github.actor }} has pushed the changes to master branch
on: [push]
jobs:
  generate-html:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "
          OS: ${{ runner.os }}
          Triggered by a ${{ github.event_name }}
          Branch: ${{ github.ref }}
          Repo: ${{ github.repository }}
          "
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          for i in md/*.md ; do echo "$i" && pandoc -s $i -o $i.html ; done
      - run: echo "ğŸ This job's status is ${{ job.status }}."