name: generate html from MDs under md directory
run-name: ${{ github.actor }} - master push
on: [push]
jobs:
  generate-html:
    runs-on: ubuntu-latest
    steps:
      - name: "Action Details ğŸš€"
      - run: |
          echo "
          Runner OS: ${{ runner.os }}
          Triggered Event: ${{ github.event_name }}
          Event By: ${{ github.actor }}
          Branch: ${{ github.ref }}
          Repo: ${{ github.repository }}
          "
      - name: Install Pandoc
        uses: pandoc/actions/setup@{main}
        with:
          version: 2.19
      # - name: Check out repository code
      #   uses: actions/checkout@v4
      - name: Build
        run: pandoc --version
      - run: echo "ğŸ This job's status is ${{ job.status }}."